### ISSUE TITLE
[I18N] Internationaliser l'application

### ISSUE THREAD

**Issue by bashizip** [JCERTIFLab/jcertif-android-2013#10]
Creer le fichier strings pour la langue FR et traduire les strings .

**Comment by lordgodgiven** [comment]
Je vais m'occuper de cette tâche

**Comment by chrisbel** [comment]
Voilà un courageux, très bonne initiative c'est très bien ....

Le jeudi 1 août 2013, lordgodgiven a écrit :

> Je vais m'occuper de cette tâche
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JCERTIFLab/jcertif-android-2013/issues/10#issuecomment-21920511
> .

## 

Excusez la brièveté et les fautes
Roland. Chrisbel
Envoyé avec Gmail Mobile

**Comment by bashizip** [comment]
Cool !

**Comment by lordgodgiven** [comment]
J'ai complété la traduction de Michel. Question SocialStreamFragment c'est bien Social Stream Fragment? Si c'est la cas Fragment Flux Social concrètement cela rime à quoi rapport à l'application.

**Comment by michelo243** [comment]
Salut,

A mon avis SocialStreamFragment c'est juste le nom d'un fragment.  Je crois
que pas des traduction pour cela.

Est-ce vrai Patrick  ?

Regards,

---

Send from my android phone.
Michel Isamuna

**Comment by bashizip** [comment]
Social ?
Facebook , Twitter , Google+ , etc
L'idée est d'embarquer des flux des réseaux sociaux dans l'application .
Voir ioshed 2013
