### ISSUE TITLE
[Référentiel] Charger les données du référentiel au premier démarage

### ISSUE THREAD

**Issue by bashizip** [JCERTIFLab/jcertif-android-2013#22]
Charger les données du référentiel au premier demarrage de l'application et les mettre en cache.
Au besoin developper un splash screen.

**Comment by bashizip** [comment]
Il n'y aura pas de splash screen (anti pattern a vrai dire) . A la place on aura un fragment d' initialisation des données. 
Scénario : check si la db est vide (premier lancement ) et Lancer InitFragment .
InitFragment à so tour envoie sequentiellement des requêtes au service (intentService). Le service retourne un bundle contenant le résultat (JSON) et l'URL envoyé pour chaque requête . Dans OnRestResult du InitFragment on met les données dans db4o.

**Comment by lordgodgiven** [comment]
@Patrick,
J'ai cloné le branch master du projet via eclipse ADT, lorsque je veux
ajouter une nouvelle resources via le wizard, je n'arrive pas à selecrionné
le projet, j'ai donc du le faire manuellement avec l'explorateur windows,
j'ai presque fini avec la traduction, je vais commiter ce soir.

Merci

Envoyer de mon androïd - Excusez la brieveté
Dieudonné NIEME

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/ff8d2cd2-9582-4beb-a4ca-df4d171b2cb3

## 

Ce message a été envoyé par Twitter à la demande d'utilisateurs de Twitter qui ont saisi votre adresse électronique pour vous inviter sur Twitter.
Se désinscrire : https://twitter.com/i/o?t=1&iid=f9cf0ac89603476fa6b929650940607f&uid=0&c=IuVwbCB3dgGpQ54dJ0eDf%2B0CBWmcmipyJtmSSGSqZUY9mFAmVEmPYXU8wYpobbGJMm8PoWj%2Fe33UNrQyoCMukNNxQP8WLAhOlam64%2By7t%2FCly%2BjPWMYc4w%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/87e49d9f-fca9-420e-8e7a-368e9516f5a1

## 

Ce message a été envoyé par Twitter à la demande d'utilisateurs de Twitter qui ont saisi votre adresse électronique pour vous inviter sur Twitter.
Se désinscrire : https://twitter.com/i/o?t=1&iid=7ce6a95050834b9d8105ecd7adf66e24&uid=0&c=IuVwbCB3dgGpQ54dJ0eDf%2B0CBWmcmipyJtmSSGSqZUY9mFAmVEmPYXU8wYpobbGJMm8PoWj%2Fe33UNrQyoCMukNNxQP8WLAhOlam64%2By7t%2FCly%2BjPWMYc4w%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/1df059eb-89b7-47e0-8593-ecb272644577

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Se désinscrire : https://twitter.com/i/o?t=1&iid=50a02aab7a6541e3a8fb80d5b905425a&uid=0&c=IuVwbCB3dgGpQ54dJ0eDf%2B0CBWmcmipyJtmSSGSqZUY9mFAmVEmPYXU8wYpobbGJMm8PoWj%2Fe33UNrQyoCMukNNxQP8WLAhOlam64%2By7t%2FCly%2BjPWMYc4w%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com

**Comment by lordgodgiven** [comment]
Dieudonné NIEME vous a envoyé une invitation

Twitter vous aide à rester en contact avec ce qui se passe en ce moment et avec les personnes et les organisations qui vous tiennent à cœur.

```
Accepter l'invitation
```

https://twitter.com/i/f5bbe7ca-f288-4108-aa24-0d8b52db4384

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Se désinscrire : https://twitter.com/i/o?t=1&iid=cb1f84d7ad714ee78e13c731345f772b&uid=0&c=IuVwbCB3dgGpQ54dJ0eDf%2B0CBWmcmipyJtmSSGSqZUY9mFAmVEmPYXU8wYpobbGJMm8PoWj%2Fe33UNrQyoCMukNNxQP8WLAhOlam64%2By7t%2FCly%2BjPWMYc4w%3D%3D&nid=9+26

Besoin d'aide ?
https://support.twitter.com
