### ISSUE TITLE
plantage à la connexion 

### ISSUE THREAD

**Issue by bigoliver** [JCERTIFLab/jcertif-android-2013#39]
Lorsqu'on essaie de se connecter en utilisant son compte google, l'application plante.

Par contre, j'ai été obligé de redémarrer la tablette pour pouvoir relancer l'application.

J'utilise android 4.0.4

**Comment by bashizip** [comment]
Modele de la tablette?

Plantage : l'app se frise ou bien se ferme en ANR (application not responding)?

Apres redemarage, ca marché?

**Comment by bigoliver** [comment]
Galaxy tab 1 10". Après redémarrage ça marche.
Le message qui s'affiche est : jcertif s'est arrêté.
La connexion avec google fait planter l'application jcertif.

**Comment by bashizip** [comment]
Ça sent plutôt problème isolé. surtout que ça marche après redémarrage. On
va attendre voir si un autre cas similaire va se produire
